stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/Train.csv
    outs:
    - data/raw/Train.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/missing_values.py
    - src/feature_encoding.py
    - src/split_data.py
    - data/raw/Train.csv
    outs:
    - data/processed/train_salespred.csv
    - data/processed/test_salespred.csv
  
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/train_salespred.csv
    - data/processed/test_salespred.csv 
    - src/train_and_evaluate.py
    params:
    - estimators.RandomForestRegressor.params.n_estimators
    metrics:
    - report/scores.json:
        cache: false
    - report/params.json:
        cache: false
    outs:
    - saved_models/model.joblib