base:
  project: StoreSales-Prediction
  random_state: 42
  target_col: Item_Outlet_Sales

data_source:
  s3_source: data_given/Train.csv

load_data:
  raw_dataset_csv: data/raw/Train.csv

split_data:
  train_path: data/processed/train_salespred.csv
  test_path: data/processed/test_salespred..csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      n_estimators: 100
      
model_dir: saved_models

reports:
  params: report/params.json
  scores: report/scores.json

webapp_model_dir: prediction_service/model/model.joblib